7.2 Self Check 2 DeeDee Walker

In [1]:
import numpy as np

In [2]:
np.array([x for x in range(2,21,2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

7.2 Self Check 3 DeeDee Walker

In [3]:
import numpy as np

In [4]:
np.array([[x for x in range(2,11,2)],[y for y in range(1,10,2)]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

7.3 Self Check 2 DeeDee Walker

In [5]:
import numpy as np

In [6]:
a = np.array([[x for x in range(2,11,2)],[y for y in range(1,10,2)]])

In [7]:
a.ndim

2

In [8]:
a.shape

(2, 5)

7.5 Self Check 2 DeeDee Walker

In [9]:
import numpy as np

In [11]:
np.arange(2,41,2).reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

7.6 Self Check 1 DeeDee Walker

In [22]:
import numpy as np

In [23]:
%timeit sum([x for x in range(10_000_000)])

506 ms ± 9.42 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [24]:
%timeit np.arange(10_000_000).sum()

10.1 ms ± 49.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


7.7 Self Check 2 DeeDee Walker

In [25]:
import numpy as np

In [26]:
np.arange(1,6) **2

array([ 1,  4,  9, 16, 25])

7.8 Self Check 2 DeeDee Walker

In [31]:
import numpy as np
grades = np.random.randint(60,101,12).reshape(3,4)
grades

array([[69, 69, 60, 69],
       [80, 75, 69, 97],
       [68, 94, 71, 82]])

In [32]:
grades.mean()

75.25

In [33]:
grades.mean(axis=1)

array([66.75, 80.25, 78.75])

In [34]:
grades.mean(axis=0)

array([72.33333333, 79.33333333, 66.66666667, 82.66666667])

7.9 Self Check 2 DeeDee Walker

Create an array of the values from 1 through 5, then use the power  universal function and broadcasting to cube each value. 

In [1]:
import numpy as np

In [2]:
numbers = np.arange(1,6)

In [3]:
np.power(numbers,3)

array([  1,   8,  27,  64, 125], dtype=int32)

7.10 Self Check 1 DeeDee Walker

In [4]:
import numpy as np

In [5]:
numbers = np.array([[ 1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15]])

In [6]:
numbers

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [7]:
#select the 2nd row
numbers[1]

array([ 6,  7,  8,  9, 10])

In [10]:
#select the 1st & 3rd rows
numbers[[0, 2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [12]:
#select the middle 3 columns
numbers[:, 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

7.13 Self Check 1 DeeDee Walker

In [12]:
import numpy as np

In [13]:
grades = np.array([[1, 2, 3],
                   [4, 5, 6]])

In [14]:
grades2 = grades.copy()

In [15]:
grades3 = np.hstack((grades, grades2))

In [16]:
np.vstack((grades3, grades3))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [17]:
#book version

In [18]:
a = np.arange(1,7).reshape(2,3)

In [19]:
a = np.hstack((a,a))

In [20]:
a = np.vstack((a,a))

In [21]:
a

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

7.14.1 Self Check 1 DeeDee Walker

In [22]:
import numpy as np

In [23]:
import pandas as pd

In [31]:
temps = np.random.randint(60,101,6)

In [32]:
temperatures = pd.Series(temps)

In [33]:
temperatures

0    91
1    97
2    93
3    88
4    94
5    74
dtype: int32

In [34]:
temperatures.min()

74

In [35]:
temperatures.max()

97

In [36]:
temperatures.mean()

89.5

In [37]:
temperatures.describe()

count     6.000000
mean     89.500000
std       8.167007
min      74.000000
25%      88.750000
50%      92.000000
75%      93.750000
max      97.000000
dtype: float64

7.14.2 Self Check 1 DeeDee Walker

In [38]:
import pandas as pd

In [39]:
temps = {'Mon': [68, 89], 'Tue': [71, 93], 'Wed': [66, 82],
         'Thu': [75, 97], 'Fri': [62, 79]}

In [40]:
temperatures = pd.DataFrame(temps, index=['Low', 'High'])

In [41]:
temperatures

Mon  Tue  Wed  Thu  Fri
Low    68   71   66   75   62
High   89   93   82   97   79

In [49]:
temperatures.loc['Low':'High',['Mon','Tue','Wed']]

Mon  Tue  Wed
Low    68   71   66
High   89   93   82

In [55]:
temperatures.loc[:,'Mon':'Wed']

Mon  Tue  Wed
Low    68   71   66
High   89   93   82

In [56]:
temperatures.loc['Low']

Mon    68
Tue    71
Wed    66
Thu    75
Fri    62
Name: Low, dtype: int64

In [51]:
temperatures.iloc[[0], 0:5]

Mon  Tue  Wed  Thu  Fri
Low   68   71   66   75   62

In [53]:
pd.set_option('display.precision',2)

In [54]:
temperatures.mean()

Mon    78.5
Tue    82.0
Wed    74.0
Thu    86.0
Fri    70.5
dtype: float64

In [57]:
temperatures.mean(axis=1)

Low     68.4
High    88.0
dtype: float64